### ISSUE TITLE
update block assignments for sevi.us plots (all currently in block 1)

### ISSUE THREAD

**Issue by nutnetadmin** [nutnetadmin/nutnet-data-tracker#1]
While analyzing full-cover-04-December.csv, I found that all 40 plots for sevi.us are listed as being in Block 1. But they should actually be in 4 blocks of 10. This problem affects the other standard datasets: comb-by-plot[..].csv and full-biomass.csv. This should be updated in the database.

**Comment by ericlind** [comment]
Not a bug - sevi.us has 4 blocks worth of treatments, but the treatments were fully randomized across all 40 plots (i.e. not spatially blocked). Thus the block was set to 1 for all of them, to prevent misleading aggregation etc. Check by something like

`SELECT FLOOR((plot+10)/10) as tempBlock, 
SUM(IF(N = 1, 1, 0)) as Nplots,
SUM(IF(P = 1, 1, 0)) as Pplots,
SUM(IF(K = 1, 1, 0)) as Kplots
FROM plot 
WHERE site_id = (SELECT site_id FROM site WHERE site_code = 'sevi.us')
GROUP BY tempBlock
;`

It should be 5 of each treatment in each block. But I don't think it is.

**Comment by nutnetadmin** [comment]
Thanks, EL. Closing this issue.
