### ISSUE TITLE
biomass categories sometimes not standardized

### ISSUE THREAD

**Issue by ghost** [nutnetadmin/nutnet-data-tracker#106]
bio3<- full-biomass-09-April-2018.csv
bio3$category[bio3$category=='FORB + PHLOX DIFFUSA']<-'FORB'

**Comment by nutnetadmin** [comment]
Not a bug: The Borer-Seabloom lab could not decide whether to put _Phlox diffusa_ in the forb category or in the woody (I think?) category, so you can talk to Seabloom about the pros/cons of each category assignment. I'll close this for now but re-open this issue if more come up!

**Comment by ghost** [comment]
Quick comment -> in "full-cover-09-April-2018" PHLOX DIFFUSA is listed as functional_group =FORB. Consider standardizing so Biomass and Cover data sets refer to it as "FORB" or "FORB + PHLOX DIFFUSA" similarly?
