### ISSUE TITLE
first_fenced_year doesn't cover all sites with fences

### ISSUE THREAD

**Issue by siddharth-bharath** [nutnetadmin/nutnet-data-tracker#110]
arch.us, burren.ie, podo.ec, potrok.ar, bayr.de - have NA values for first_fenced_year

```{r }
library(tidyverse)
library(data.table); library(dtplyr)
biomass_data <- data.table(read.csv("~/Dropbox/Comp-Sync/Projects/Nutnet_base_data/comb-by-plot-09-April-2018.csv",na.strings=c('NULL','NA','')))
sites <- biomass_data %>% group_by(site_code) %>% summarise(exclose=max(Exclose),yrs.data = length(unique(year)),fyear = min(year),first_fenced_year=mean(first_fenced_year),
                                                            min.year_trt=min(year_trt),max.year_trt=max(year_trt), lyear = max(year))
print(sites[exclose==1 & is.na(first_fenced_year),`site_code'])
```

**Comment by nutnetadmin** [comment]
arch.us: fences installed 5/23/2016
burren.ie (Slieve Carran): fences installed March 2016
podo.ec - first data year was 2015, have not yet received 2016 data
bayr.de - first year was 2016; in 2016 data said they will fence 2017-04-15; have not yet received 2017 data

I will go ahead and update first_fenced_year for burden and arch, but wait until data from podo and bayr come in before I update those sites. (Sometimes people don't manage to get the fences up when they want to).

fixed 24-august-2018 on-the-fly (no script saved).

thank you siddharth!!!
