### ISSUE TITLE
Change lat-longs for cowi.ca, saana.fi, kilp.fi, comp.pt

### ISSUE THREAD

**Issue by siddharth-bharath** [nutnetadmin/nutnet-data-tracker#148]
Based on responses from site PIs to the daily weather data survey, please change the lat-longs for the following sites - 

'cowi.ca', site_lat:=48.8088, site_long:=(-123.6301)
'saana.fi', site_lat:=69.0567, site_long:=(20.8747)
'kilp.fi', site_lat:=69.0368, site_long:=(20.8433)
'comp.pt', site_lat:=38.82928, site_long:=(-8.791406)

**Comment by nutnetadmin** [comment]
Thank you @iyengar-siddharth !

**Comment by nutnetadmin** [comment]
fixed on 25-Feb-2019
no script saved, fixed on the fly

**Comment by nutnetadmin** [comment]
fixed on 25-feb-2019
no script saved, fixed on the fly
