### ISSUE TITLE
upload new sampling data: hustai.mn 2018-2020 (Year 0-2)

### ISSUE THREAD

**Issue by nutnetadmin** [nutnetadmin/nutnet-data-tracker#155]
received from Cini brown 24-March-2019
Saved to 2018 working directory

**Comment by nutnetadmin** [comment]
used better worldclim coordinates to upload climate data; site info is all complete now

**Comment by nutnetadmin** [comment]
Updated Hustai data submitted. 2018 has plot designation fixes. Correct file is 'Hustai 2018.xlsx' in 2018 to import file. 2019 and 2020 data are in their respective folders as well

**Comment by nutnetadmin** [comment]
Cover and par uploaded. Waiting to hear back fro Ariuna and Cini about correct scale for biomass, and then can finish the site upload.

**Comment by nutnetadmin** [comment]
Biomass reported in g/0.2m2 per Ariuna.

**Comment by pawilfahrt** [comment]
Uploaded with 'import-hustai-2018-2020.sql'
