### ISSUE TITLE
sval.no year_trt incorrect

### ISSUE THREAD

**Issue by habacucfm** [nutnetadmin/nutnet-data-tracker#236]
sval.no year_trt == 999999, perhaps 999999 == NA?

**Comment by nutnetadmin** [comment]
Oh yeah I remember that one! It's actually "-2." They sampled, then couldn't return to their site for whatever reason, then sampled again & did the experiment. This is like a pre-, pre-, pre-treatment sampling.

**Comment by nutnetadmin** [comment]
fixed by changing the view to accommodate negative values of year_trt (cast as signed)

```
  IF(ISNULL(`t5`.`First_nutrient_year`),
            0,
            (CAST((`t1`.`year` + 1) AS SIGNED) - CAST(`t5`.`First_nutrient_year` AS SIGNED))) AS `year_trt`,
```
