### ISSUE TITLE
Negative values in pctN and ppmP?

### ISSUE THREAD

**Issue by habacucfm** [nutnetadmin/nutnet-data-tracker#241]
@nutnetadmin this seems odd to me, is it correct?

**Comment by nutnetadmin** [comment]
oooo definitely no.
thank you for catching this!

**Comment by nutnetadmin** [comment]
Hi Haba, I'm not seeing this error. Where are you seeing this?
Looked in:
- comb-by-plot-clim-soil-diversity-02-Aug-2019.csv
- soil-nutrients-22-February-2019.csv

I also checked the raw data in the database. Let me know where (in which files, observations) this is popping up, probably an easy fix!

**Comment by habacucfm** [comment]
@nutnetadmin PICNIC. Data is OK, was a transformation....
