### ISSUE TITLE
check marc.ar biomass values: total in full_biomass does not correspond to totals in raw data

### ISSUE THREAD

**Issue by ashleyasmus** [nutnetadmin/nutnet-data-tracker#26]
First flagged by Carlos Alberto Arnillas when he did an analysis of graminoid biomass compared to graminoid cover. I checked against the raw data files and found that the raw data for 2012 do not match what is in full_biomass[DATE].csv. This could be for one of two reasons:
(1) Technically, marc.ar measured biomass twice in 2012, once in January and once in December. The December 2012 harvest should be == year 2012; the January harvest should be == year 2011. Because marc.ar harvests so close to the turn of the year, we should make sure that we have assigned the correct "treatment year" to the biomass values.
(2) marc.ar reports biomass values to us by a mixture of functional group categories and species categories. we should make sure that we have aggregated up to to functional group level appropriately each year.

**Comment by juanalberti** [comment]
Hi nutnetadmin ;) 
it is definitely your second option. I just checked the original files (submitted with biomass per species) and for some reason the biomass estimates went wrong when aggregated into grass/forb/etc.

**Comment by nutnetadmin** [comment]
fixed in fix-marc-biomass-2011-2012.sql
